### ISSUE TITLE
Program stalls at handle REST routine

### ISSUE THREAD

**Issue by MAKA69** [switchdoclabs/OurWeatherWeatherPlus#12]
8 minutes after booting and connecting to Wifi the software stalls.  Actually it gets stuck in the main loop. I use Arduino 1.8.1 and installed v023.

  WiFiClient client = server.available();
  if (client)  {
    while (!client.available()) {  // potential infinite loop
      delay(1);
    }
    if (client.available()) {
      rest.handle(client);
    }
  }

By adding a counter and a break point at the while (!client.available()) loop it runs like a charm.

    while (!client.available()) {
       Serial.print(".");    
       delay(1);   
       timeout++;
        if(timeout>1000) {Serial.print("INFINITE LOOP BREAK!");  break;}
    }

**Comment by switchdoclabs** [comment]
Thanks!  Incorporated in V024

BP
