### ISSUE TITLE
String.h not found on compile in Arduino IDE

### ISSUE THREAD

**Issue by YannChemin** [switchdoclabs/OurWeatherWeatherPlus#2]
Hi,

I am using Arduino IDE, and it bugs on String.h, 
I have checked that Arduino.h is found in the same .ino file (few lines above).
Using Arduino 1.8.2 with the genericESP8266 board and the default compiler (AVRISP mkII).

Thanks for any suggestions,
Yann

**Comment by switchdoclabs** [comment]
You need to make sure you have downloaded and selected the adafruit huzzah ESP8266 libraries

**Comment by YannChemin** [comment]
I have not been able to find those libraries, 
only those related things: https://github.com/adafruit?utf8=%E2%9C%93&q=HUZZAH&type=&language=

any link plz

-----------------------------
/OurWeatherWeatherPlus/trunk/SDL_ESP8266_WeatherPlus/SDL_ESP8266_WeatherPlus.ino:86:20: fatal error: String.h: No such file or directory
 #include <String.h>
                    ^
compilation terminated.
exit status 1
Error compiling for board Adafruit HUZZAH ESP8266.

**Comment by switchdoclabs** [comment]
Instructions:

https://www.adafruit.com/product/2471

**Comment by YannChemin** [comment]
Yes I have included the ESP8266 boards listing and libraries already from the boards manager, and I selected that HUZZAH board (see previous message last line).
in Sketch-> Libraries -> I can find several ESP8266 things, but nothing mentioning HUZZAH.

**Comment by switchdoclabs** [comment]
Did you try installing g the string.h library?

**Comment by YannChemin** [comment]
You mean String.h ? or string.h ? the code looks for String.h

**Comment by YannChemin** [comment]
by renaming String.h to string.h it moves on the next missing library (ellapsedMillis.h)

**Comment by switchdoclabs** [comment]
String.h

**Comment by switchdoclabs** [comment]
Did you follow the readme file?

It sound like you are missing a bunch of libraries.

**Comment by YannChemin** [comment]
yeah it compiled after other libraries were added. it actually worked with string.h. from v17 to v21 now :-)

**Comment by switchdoclabs** [comment]
:). '
